---
- name: Install Radarr
  community.docker.docker_container:
    name: radarr-4k
    image: lscr.io/linuxserver/radarr
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      TZ: "{{ timezone }}"
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
    volumes:
      - "{{ apps_dir }}/radarr-4k/config:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: web
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr-4k.entrypoints: "http"
      traefik.http.routers.radarr-4k.rule: "Host(`4k.radarr.{{ domain }}`)"
      traefik.http.middlewares.radarr-4k-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.radarr-4k.middlewares: "radarr-4k-https-redirect"
      traefik.http.routers.radarr-4k-secure.entrypoints: "https"
      traefik.http.routers.radarr-4k-secure.rule: "Host(`4k.radarr.{{ domain }}`)"
      traefik.http.routers.radarr-4k-secure.tls: "true"
      traefik.http.routers.radarr-4k-secure.tls.certresolver: "cloudflare"
      traefik.http.routers.radarr-4k-secure.service: "radarr-4k"
      traefik.http.services.radarr-4k.loadbalancer.server.port: "7878"
      traefik.docker.network: "web"