---
- name: Create Media stack directory
  ansible.builtin.file:
    state: directory
    path: "{{ media_dir }}"
    owner: "1000"
    group: "1000"
    mode: 0770

- name: Create Media stack subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ media_dir }}/{{ item }}"
    owner: "1000"
    group: "1000"
    mode: 0770
  loop:
    - torrents
    - torrents/shows/hd
    - torrents/shows/4k
    - torrents/shows/anime
    - torrents/movies/hd
    - torrents/movies/4k
    - media
    - media/shows
    - media/anime
    - media/movies

- name: Install Radarr HD
  ansible.builtin.include_tasks: hd.yml

- name: Install Radarr 4K
  ansible.builtin.include_tasks: 4k.yml