---
- name: Essentials, Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Essentials, Install Ansible PIP packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

- name: Essentials, create docker directories
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Essentials, create media directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ data_dir }}"
    - "{{ data_dir }}/torrents"
    - "{{ data_dir }}/media"
    - "{{ data_dir }}/media/movies"
    - "{{ data_dir }}/media/tv"
    - "{{ data_dir }}/media/anime"
    - "{{ data_dir }}/torrents/movies"
    - "{{ data_dir }}/torrents/tv"
    - "{{ data_dir }}/torrents/anime"

- name: Create Apps directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ docker_dir }}/socket-proxy"
    - "{{ docker_dir }}/traefik-proxy"
    - "{{ docker_dir }}/portainer"
    - "{{ docker_dir }}/jellyfin"
    - "{{ docker_dir }}/qbittorrent"
    - "{{ docker_dir }}/prowlarr"
    - "{{ docker_dir }}/radarr"
    - "{{ docker_dir }}/sonarr"
    - "{{ docker_dir }}/uptime"
    - "{{ docker_dir }}/jellyseerr"
    - "{{ docker_dir }}/mariadb"
    - "{{ docker_dir }}/phpmyadmin"
    - "{{ docker_dir }}/phpmyadmin/themes"
    - "{{ docker_dir }}/speedtest-tracker"
