---
- name: Initialize Carthage
  hosts: localhost
  become: true

  tasks:
    - name: Essentials, install Core...
      ansible.builtin.include_tasks: tasks/essential.yml

    - name: Essentials, install Docker
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: Install Database Apps
      ansible.builtin.include_tasks: "tasks/database/{{ item }}.yml"
      loop:
        - mariadb
        - phpmyadmin

    - name: DockerApps, install core
      ansible.builtin.include_tasks: "tasks/essentials/{{ item }}.yml"
      loop:
        - socket_proxy
        - traefik_proxy
        - portainer
        - uptime
        - speedtest_tracker

    - name: DockerApps, install Media Apps
      ansible.builtin.include_tasks: "tasks/media/{{ item }}.yml"
      loop:
        - jellyfin
        - qbittorrent
        - prowlarr
        - sonarr
        - radarr
        - jellyseerr

    - name: Modify ownership of data and docker_apps directories
      ansible.builtin.include_tasks: tasks/add_ownership.yml