---
- name: Setup PhpMyAdmin Theme, Dark Wolf
  ansible.builtin.unarchive:
    src: "https://files.phpmyadmin.net/themes/darkwolf/5.2/darkwolf-5.2.zip"
    dest: "{{ docker_dir }}/phpmyadmin"
    creates: "{{ docker_dir }}/phpmyadmin/themes/darkwolf"
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  
- name: Setup PhpMyAdmin
  community.docker.docker_container:
    name: phpmyadmin
    image: phpmyadmin:latest
    restart_policy: always
    state: started
    networks:
      - name: carthage
      - name: mariadb
    volumes:
      - "{{ docker_dir }}/phpmyadmin/themes:/var/www/html/themes"
    env:
      DB_HOST: "mariadb"
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      PMA_ABSOLUTE_URI: "https://devtools.{{ domain }}/pma"
    labels:
      traefik.enable: "true"
      traefik.http.routers.pma.entrypoints: "http"
      traefik.http.routers.pma.rule: "Host(`devtools.{{ domain }}`) && Path(`/pma`))"
      traefik.http.middlewares.pma-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.pma.middlewares: "pma-https-redirect"
      traefik.http.routers.pma-secure.entrypoints: "https"
      traefik.http.routers.pma-secure.rule: "Host(`devtools.{{ domain }}`) && Path(`/pma`))"
      traefik.http.routers.pma-secure.tls: "true"
      traefik.http.routers.pma-secure.service: "pma"
      traefik.docker.network: "carthage"