---
- name: Setup PhpMyAdmin Theme, Dark Wolf
  ansible.builtin.unarchive:
    src: "https://files.phpmyadmin.net/themes/darkwolf/5.2/darkwolf-5.2.zip"
    dest: "{{ docker_dir }}/phpmyadmin"
    creates: "{{ docker_dir }}/phpmyadmin/themes/darkwolf"
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  
- name: Setup PhpMyAdmin
  community.docker.docker_container:
    name: phpmyadmin
    image: phpmyadmin:latest
    restart_policy: always
    state: started
    networks:
      - name: carthage
      - name: mariadb
    volumes:
      - "{{ docker_dir }}/phpmyadmin/themes:/var/www/html/themes"
    env:
      DB_HOST: "mariadb"
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      PMA_ABSOLUTE_URI: "https://devtools.{{ domain }}/phpmyadmin"
    labels:
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin.entrypoints: "http"
      traefik.http.routers.phpmyadmin.rule: "Host(`devtools.{{ domain }}`) && PathPrefix(`/phpmyadmin`)"
      traefik.http.middlewares.phpmyadmin-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.phpmyadmin.middlewares: "phpmyadmin-https-redirect"
      traefik.http.routers.phpmyadmin-secure.entrypoints: "https"
      traefik.http.routers.phpmyadmin-secure.rule: "Host(`devtools.{{ domain }}`) && PathPrefix(`/phpmyadmin`)"
      traefik.http.routers.phpmyadmin-secure.tls: "true"
      traefik.http.routers.phpmyadmin-secure.service: "phpmyadmin"
      traefik.http.routers.phpmyadmin.middlewares: "pma-stripprefix"
      traefik.http.middlewares.pma-stripprefix.stripprefix.prefixes: "/phpmyadmin"
      # traefik.http.routers.jellyfin-secure.middlewares: "authelia@docker"
      traefik.http.services.phpmyadmin.loadbalancer.server.port: "80"
      traefik.docker.network: "carthage"