---
- name: Setup docker host
  community.docker.docker_network:
    name: database
    state: present
    driver: bridge

- name: Setup Maria DB
  community.docker.docker_container:
    name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart_policy: always
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      MYSQL_USER: "{{ mariadb_username }}"
      MYSQL_PASSWORD: "{{ mariadb_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MYSQL_DATABASE: "carthage"
    networks:
      - name: database
    volumes:
      - "{{ docker_dir }}/mariadb:/config"