---
- name: Create Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    pull: true
    state: started
    restart_policy: unless-stopped
    command: "-H tcp://socket-proxy:2375"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/portainer/data:/data"
    security_opts:
      - no-new-privileges:true
    networks:
      - name: socket_proxy
      - name: carthage
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ domain }}`)"
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.portainer.middlewares: "portainer-https-redirect"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`portainer.{{ domain }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "portainer"
      # traefik.http.routers.portainer-secure.middlewares: "authelia@docker"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.docker.network: "carthage"